### ISSUE TITLE
dataset_HSI

### ISSUE THREAD

**Issue by xh-captain** [hkzhang91/LWNet#1]
请问，您的预处理的数据集调用HSI_dataset这个文件缺少，是要调用数据集运行那一部分代码吗？还是这个文件缺失？谢谢

**Comment by xh-captain** [comment]
No such file or directory: '../../../data/HSI_datasets/samples/Indian/samples_52_36.npy'一直在报这个错误，抱歉打扰，我在寻找是否有未发现的文件，请您方便的话，帮助一下我，谢谢

**Comment by hkzhang-git** [comment]
solved
